version: '2.1'

services:
  #service 1: mysql database image creation
  db:
    image: mysql:latest
    container_name: skp
    environment:
      - MYSQL_ROOT_PASSWORD=siva
    ports:
      - "3307:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


  # service 2:
  employeeapp:
    image: sivavk/employee-service
    container_name: employee-service-app     # name of container created from image
    build:
      context: .                          # path to docker file
      dockerfile: Dockerfile              # docker file name
    ports:
      - "8081:8080"                       # notebook service port
    restart: always

    depends_on:                           #define dependencies of this app
      db :                              #dependency name (which is defined with this name 'db' in this file earlier)
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://skp:3306/employee?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: siva